
#openai
api_key: "sk-MU84NXm5WbkP******451d8e06Dc3448F9F7F0"  # 确保这里放的是正确的API密钥
base_url: "https://api.aiskt.com/v1"
model: "gpt-4o-2024-05-13"

#deepseek
#api_key: "sk-359d******b392078f1ec5294a36"  # 确保这里放的是正确的API密钥
#base_url: "https://api.deepseek.com/v1"
#model: "deepseek-chat"
